# Generated by Django 3.0.4 on 2020-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
