# Generated by Django 3.0.4 on 2020-03-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200315_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='photo',
        ),
    ]
