# Generated by Django 3.0.4 on 2020-03-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
    ]
